"""Initial schema: users, books, borrowings, reservations, org settings

Revision ID: a062ad0fb313
Revises: 
Create Date: 2026-07-30 12:44:45.861073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a062ad0fb313'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('isbn', sa.String(length=13), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('publisher', sa.String(length=100), nullable=True),
    sa.Column('publication_year', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('available_quantity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_book_author'), ['author'], unique=False)
        batch_op.create_index(batch_op.f('ix_book_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_book_isbn'), ['isbn'], unique=True)
        batch_op.create_index(batch_op.f('ix_book_title'), ['title'], unique=False)

    op.create_table('organization_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_name', sa.String(length=80), nullable=False),
    sa.Column('logo_filename', sa.String(length=120), nullable=True),
    sa.Column('theme_color', sa.String(length=7), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('member_since', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('borrowing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('borrow_date', sa.DateTime(), nullable=True),
    sa.Column('return_date', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('renewal_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('borrowing', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_borrowing_book_id'), ['book_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_borrowing_user_id'), ['user_id'], unique=False)

    op.create_table('reservation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('reservation_date', sa.DateTime(), nullable=True),
    sa.Column('expiration_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reservation_book_id'), ['book_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservation_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservation_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reservation_user_id'))
        batch_op.drop_index(batch_op.f('ix_reservation_status'))
        batch_op.drop_index(batch_op.f('ix_reservation_book_id'))

    op.drop_table('reservation')
    with op.batch_alter_table('borrowing', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_borrowing_user_id'))
        batch_op.drop_index(batch_op.f('ix_borrowing_book_id'))

    op.drop_table('borrowing')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    op.drop_table('organization_settings')
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_book_title'))
        batch_op.drop_index(batch_op.f('ix_book_isbn'))
        batch_op.drop_index(batch_op.f('ix_book_category'))
        batch_op.drop_index(batch_op.f('ix_book_author'))

    op.drop_table('book')
    # ### end Alembic commands ###
